Resolving conflicts
Code-Deeper/code-sync pull request #117
Opened 2021-12-20 06:27 UTC by MadhuSaini22

2021-12-20 06:36 UTC, akshita-kamani commented
Hey @MadhuSaini22 , Seems like this work already had done in main branch.

Kindly resolve your conflict by taking pull from main branch ```git pull origin main```

[Image tour](https://github.com/Code-Deeper/code-sync/blob/main/imageTour.md)

2021-12-20 06:39 UTC, MadhuSaini22 commented
> Hey @MadhuSaini22 , Seems like this work already had done in main branch.
> 
> Kindly resolve your conflict by taking pull from main branch `git pull origin main`
> 
> [Image tour](https://github.com/Code-Deeper/code-sync/blob/main/imageTour.md)

hello @akshita-kamani , there are not conflicts now. They found previously but I had fixed them. You can merge now

2021-12-21 04:42 UTC, akshita-kamani requested changes

2021-12-21 04:42 UTC, akshita-kamani commented on assets/Readme.md
> +# Image Tour of entire Application☣️
No need to write in ```assets/Readme.md``` because there is already had in ```imageTour.md``` file. You can checkout this file and got idea :)

2021-12-21 04:42 UTC, akshita-kamani commented
As of now, features is already done. So i am closing this PR. @MadhuSaini22 Thank you for your contribution :1st_place_medal:

2021-12-21 04:43 UTC, closed without merging