Add forgot & reset password components
Code-Deeper/code-sync pull request #119
Opened 2021-12-26 15:38 UTC by iamrahulrnair

Hey , i have added forgot and reset password components, but not sure regarding the style,  @akshita-kamani  told about reviewing the style, i have  implemented the components, but a major refactor will be required to get the ui to work  properly,This is because i am not sure of some states and what they do, Thanks :-)

2022-01-08 03:27 UTC, codewithvk requested changes

2022-01-08 03:27 UTC, codewithvk commented on client/src/App.js
> +          <Route path='/reset_password/:id' exact component={ResetPassword} />
```<Route path='/_reset_password/:id' exact component={ResetPassword} />```

2022-01-08 03:27 UTC, codewithvk commented on client/src/Components/Auth/ForgotPassword/ForgotPassword.js
> +      await axios.post('/api/_forgot_password', {
Use ```AXIOS``` instead of ```Axios```

2022-01-08 03:27 UTC, codewithvk commented on client/src/Components/Auth/ResetPassword/ResetPassword.js
> +import axios from 'axios';
```import AXIOS from '../../../API'```

2022-01-08 03:27 UTC, codewithvk commented on client/src/Components/Auth/ResetPassword/ResetPassword.js
> +        await axios.post(`/api/_reset_password/${JWT_KEY}`);
PassParametes password and confirm password, Also modify back-end route get to post.

2022-01-19 03:31 UTC, iamrahulrnair commented
hey done, thanks!!

2022-01-24 17:40 UTC, codewithvk approved these changes
@iamrahulrnair I reviewed your entire code. LGFM.🥇

Thanks for contribution and apologize for late response.

2022-01-24 17:40 UTC, merged